apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote-deployment
  name: vote-deployment
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vote-deployment
    spec:
      containers:
      - image: kodekloud/examplevotingapp_vote:before
        name: examplevotingapp-vote
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vote-service
  name: vote-service
  namespace: vote
spec:
  ports:
  - name: 5000-80
    nodePort: 31000
    port: 5000
    protocol: TCP
    targetPort: 80
  selector:
    app: vote-deployment
  type: NodePort
status:
  loadBalancer: {}